### ISSUE TITLE
java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "png_set_longjmp_fn" referenced by ....

### ISSUE THREAD

**Issue by tagantroy** [julienr/libpng-android#3]
java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "png_set_longjmp_fn" referenced by "libExample.so"...
            at java.lang.Runtime.loadLibrary(Runtime.java:364)
            at java.lang.System.loadLibrary(System.java:526)
            at com.example.ARActivity.<clinit>(ARActivity.java:92)
            at java.lang.Class.newInstanceImpl(Native Method)
            at java.lang.Class.newInstance(Class.java:1208)
            at android.app.Instrumentation.newActivity(Instrumentation.java:1061)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2101)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233)
            at android.app.ActivityThread.access$800(ActivityThread.java:135)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5001)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
            at dalvik.system.NativeStart.main(Native Method)

Problem on nexus 5 with 4.4 android.

**Comment by julienr** [comment]
Do you compile libpng as a shared library ? If yes, do you load the library with `System.loadLibrary("libpng")` (in addition to your libExample) ?

**Comment by tagantroy** [comment]
Android.mk
include $(CLEAR_VARS)
LOCAL_MODULE := libpng
LOCAL_SRC_FILES = $(LIBRARIES_PATH)/android/libpng.so
include $(PREBUILT_SHARED_LIBRARY)

private static final String NATIVE_LIB_LIBPNG = "png";
private static final String NATIVE_LIB_EXAMPLE = "Example";
static{
...
 System.loadLibrary(NATIVE_LIB_LIBPNG);
...
 System.loadLibrary(NATIVE_LIB_EXAMPLE);
}

**Comment by tagantroy** [comment]
static library - working fine.
shared library - crash on 4.4 android.
